workspace:
  base: /go
  path: src/github.com/avijit-dgp/repositories-to-be-tested-by-drone

pipeline:
  test:
    image: golang:latest
    commands:
      - go get
      - go test -v -cover
  build:
    image: golang:latest
    commands:
      - go build
